{% set version = "3.0.2" %}

package:
  name: bgen_reader
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bgen-reader/bgen-reader-{{ version }}.tar.gz
  sha256: 1c0bf5983b14e84b70b3b5465bacdf92cbcf37138be86c9bc10e8960b545a402

build:
  number: 0
  skip: true  # [win and py27]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - bgen >=3.0.2
    - cffi >=1.11.5
    - pip
    - pytest-runner >=4.2
    - python
    - setuptools >=38.4.0
  run:
    - bgen >=3.0.2
    - cffi >=1.11.5
    - dask >=1.0.0
    - pandas >=0.23.4
    - pytest >=3.3.2
    - python
    - scipy >=1.2.0
    - toolz >=0.9.0
    - tqdm >=4.19.5
    - xarray >=0.11.2
    - texttable >=1.5.0
    - cachetools >=3.0.0

test:
  requires:
    - pytest
  imports:
    - pandas
    - bgen_reader
  commands:
    - python -c "import sys; import pandas; import bgen_reader; sys.exit(bgen_reader.test())"

about:
  home: https://github.com/limix/bgen-reader-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'A BGEN file format reader'
  description: |
    BGEN is a file format for storing large genetic datasets.
    It supports both unphased genotypes and phased haplotype data with variable
    ploidy and number of alleles. It was designed to provides a compact data
    representation without sacrificing variant access performance.
  doc_url: https://github.com/limix/bgen-reader-py
  dev_url: https://github.com/limix/bgen-reader-py

extra:
  recipe-maintainers:
    - Horta
