travis:
  secure:
    BINSTAR_TOKEN: GFyOnKFsqQgLIPYT65G9Y1cVlxDUhDv6vuHxXIWQpVnCVAK91zMsVKjy3/n9+6QJeMKkqwMSBP108S2BRIvF6BXaie6IjZkgwnc4Tu2IGH5BVsrtc8fh0Yd82EbjoyckSO8gveUjpBtjMm5LRMkeon46vrHEh2izEeJi/Dq8eZUtbCZXgcJggsrQKpwI76ru4Zkg9wzGYxYOC2+IT2dVcMxdmcY1Ag8eDCOG/gFm2OuJm8TaeoSCWJf50M0vkmen4Q+fi1/pxpCj0ZQFNrN7No9gboa+iOD7YGolMyXyzAESgKoHsZyPlrMmP2/68kjK7Lu5OW5IPU53e/6nAdgGWgS8kMIW7/KNB08wcstVROvRbT44JHLzgh7NiVkx3BphvDg3i8sCRLyBeEno0BR4GxyW1+/SDN8MU8UWLmhNyc1rgnD7qfiSr1YIgZ3/fT0Me3ym8yWrUyylErE6SqZi26F/SO23xS6DBsCseM9l2uPUvbLZ16ISwjCV7kg8Yn5/lb7J/IWWzEUgmbqtI4LsbNPdTECJmWOzXs/hVY9c9Yj4g5u+850dua4e+ruouwcbF9CAmIP3R1alWA6C8G8h5cb8ZYlkXt0zs+OnytcgRJiUtZinQXrz94PzdRcXNolxitloylOr4i8fHLgJLdc1vJ+/VsywdGPtbKWYe9IswAs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
