travis:
  secure:
    BINSTAR_TOKEN: ZrTaGEJ2gUGGa0MlcAdOgUaHo7Udkb7GpBApd9tGDZ+90b654tXK9kf3UA5Dka+NtQuGUDPJdOFMdkTPqbfI1xikp43+bvwLyoSOsfmmDlHeURaqwSEDicH1/8rKSpjjJNbkqZfNtqHSlw7s9ghum378tvDsD5JCk9DOjouVhRcW2GJk4wjvylyzZMlJI/ysjf4Uw01r3VXpxUMUGoiWBIi+4zpJRBsQV7S08CuwkLL/N1Xs+SbLJRCchMpj3/bsFnSeX5GVrp5jc1gp1SI1yq1MjX+dTX8iz48MW/YWQWarCmruGnxn0RqMksVqdMCbPjlmy2pjoHTIQpPPySXzAn12m+vPgCv05zDPeXISJ34xzK1dSbwtes5QvywReXewhNHkF13Jph6hLb4YlzOA6GLYHKodLQH88DpznWdw5cTtXm9wet5ptXPWYePJdptIwcFb9Jg2u9gprLXEh2upt+/wc5SZ1Tt4Uz1t8e1hA3PIiIimjIPnZf2STeqpeK1qbtX91urpFTEcHVwruQP7udQVcP6NmeWz4m2fTEmMdJONYIlJM+qf4dIX3/rb5mh2ixMsGkG8pCg/OYGbHUuL4ZspP/a9UVbYkjxL8l9fR896OJdtTGK7TERGStaNCKA/RqCU5sxxZPGizjNpw7SlieH56eBsSR5GHxwv/zGg0SU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
